services:
  nimbus:
    image: nimbus
    build:
      context: ./nimbus
      dockerfile: ./Dockerfile.nimbus
    container_name: nimbus-nimbus-debug
    command: ["sh", "-c", "pip install debugpy -t /tmp
              && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 main.py "]
    ports:
      - 5678:5678
      - 5000:5000
    networks:
      - web-network

  nimbus-webui:
    image: nimbus-webui
    build:
      context: ./nimbus-webui
      dockerfile: ./Dockerfile.webui
    container_name: nimbus-webui-debug
    command: ["sh", "-c", "pip install debugpy -t /tmp
               && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5679 app/app.py"]
    ports:
      - "5002:5002"
      - "5679:5679"
    environment:
      - FLASK_APP=app/app.py
      - NIMBUS_HOST=nimbus
      - NIMBUS_PORT=5002
    networks:
      - web-network
    depends_on:
      - nimbus

networks:
  web-network: