# Development Docker Compose
# Backend services only - Gazebo runs natively in WSL2
# ROS2 communication via host networking for WSL2 integration

services:
  # Central ROS2 + RTAB-Map Container
  ros2-central:
    image: ros:jazzy
    container_name: ros2-central
    ports:
      - "9090:9090"    # Rosbridge WebSocket
      - "7400:7400"    # DDS discovery
      - "7401:7401"    # DDS data
    networks:
      ros2-network:
        ipv4_address: 192.168.8.102
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - ROS2_HOSTNAME=192.168.8.102
      - ROS_AUTOMATIC_DISCOVERY_RANGE=SUBNET
      - ROS_STATIC_PEERS=192.168.8.102
    volumes:
      - ./ros2-config:/ros2_ws/src/nimbus_config
      - ./docker/cyclonedx.xml:/ros2_ws/cyclonedx.xml
    privileged: true
    command: ["bash", "-c", "source /opt/ros/jazzy/setup.bash && apt update && apt install -y ros-jazzy-rosbridge-suite ros-jazzy-rmw-cyclonedds-cpp && ros2 run rosbridge_server rosbridge_websocket --ros-args -p port:=9090 & tail -f /dev/null"]
    stdin_open: true
    tty: true

  # Ollama LLM Container
  ollama:
    image: ollama/ollama:latest
    container_name: nimbus-ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    networks:
      ros2-network:
        ipv4_address: 192.168.8.104
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  ros2-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.8.0/24
          gateway: 192.168.8.1

volumes:
  ollama:
    external: true