# Development Docker Compose
# Backend services only - Gazebo runs natively in WSL2
# ROS2 communication via host networking for WSL2 integration

services:
  # Central ROS2 + RTAB-Map Container
  ros2-central:
    image: ros:jazzy
    container_name: ros2-central
    ports:
      - "9090:9090"    # Expose rosbridge for Windows nimbus-ai
    networks:
      - nimbus-network
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedx_cpp
      - ROS_LOCALHOST_ONLY=0
    volumes:
      - ./ros2-config:/ros2_ws/src/nimbus_config
    privileged: true
    command: ["bash", "-c", "source /opt/ros/jazzy/setup.bash && apt update && apt install -y ros-jazzy-rosbridge-suite ros-jazzy-rmw-cyclonedds-cpp && ros2 run rosbridge_server rosbridge_websocket --ros-args -p port:=9090 & tail -f /dev/null"]
    stdin_open: true
    tty: true

  # Ollama LLM Container
  ollama:
    image: ollama/ollama:latest
    container_name: nimbus-ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    networks:
      - nimbus-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  nimbus-network:
    driver: bridge
  wsl2-bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24  # Predictable subnet for WSL2 access

volumes:
  ollama:
    external: true